### ISSUE TITLE
Write XLS sofia file and upload to Ona

### ISSUE THREAD

**Issue by urbanslug** [goodbotai/sofia#12]
Write an XLS file that coincides with Sofia questions and upload it to Ona. 
This way submissions from the bot can be made into Ona.
Sofia is made up of 5 bots under one, it would be best (for simplicity's sake) to have each have it's own XLSForm

- [x] FCI
- [ ]  SRQ 20
- [ ] Caregiver knowledge
- [ ] PSED
- [ ] Procedural memory

**Comment by pld** [comment]
other XLS files moved to new issues:

https://github.com/goodbotai/sofia/issues/13
https://github.com/goodbotai/sofia/issues/14
https://github.com/goodbotai/sofia/issues/15
https://github.com/goodbotai/sofia/issues/16
